<div class="panel panel-default">
  <div class="panel-body">
		<form class="form-horizontal">
		  <fieldset>
		    <legend>Contactez-nous</legend>
		    <div class="form-group">
		      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
		      <div class="col-lg-10">
		        <input type="text" class="form-control" id="inputEmail" placeholder="Email">
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="select" class="col-lg-2 control-label">Sujet</label>
		      <div class="col-lg-10">
		        <select class="form-control" id="select">
		          <option>Demande d'information</option>
		          <option>Besoin d'aide</option>
		          <option>Recrutement</option>
		          <option>Autre</option>
		        </select>
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="textArea" class="col-lg-2 control-label">Message</label>
		      <div class="col-lg-10">
		        <textarea class="form-control" rows="3" id="textArea"></textarea>
		      </div>
		    </div>
		    <div class="form-group">
		      <div class="col-lg-10 col-lg-offset-2">
		        <button type="reset" class="btn btn-default">Annuler</button>
		        <button type="submit" class="btn btn-primary">Envoyer</button>
		      </div>
		    </div>
		  </fieldset>
		</form>
	</div>
</div>

</div>


    <?php var_dump($user); ?>
</div>
