<?php
$title = 'Archiver un produit';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Êtes-vous sûr·e de vouloir archiver ce produit : 
  '<?php echo $this->escapeHtml($produit->nom); ?>' ?
</p>
<?php 
$url = $this->url('produit', array('action' => 'delete', 'id_prod'=>$this->id_prod)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id_prod" value="<?php echo (int)$produit->id_prod; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>
