<?php
$title = 'Editer un produit';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', 
    $this->url('produit', array('action' => 'edit', 'id_prod'=>$this->id_prod)));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id_prod')) . PHP_EOL;
echo $this->formRow($form->get('nom')) . PHP_EOL;
echo $this->formRow($form->get('reference')) . PHP_EOL;
echo $this->formRow($form->get('description')) . PHP_EOL;
echo $this->formRow($form->get('url_img')) . PHP_EOL;
echo $this->formRow($form->get('prix')) . PHP_EOL;
echo $this->formRow($form->get('bl_archive')) . PHP_EOL;
echo $this->formRow($form->get('bl_nouv')) . PHP_EOL;
echo $this->formRow($form->get('bl_best')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

