<?php 
$title = 'Produits';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="/admin<?php echo $this->url('produit', array( 
        'action'=>'add'));?>">Ajouter un produit</a></p>

<table class="table">
<tr>
    <th>Nom</th>
    <th>Reference</th>
    <th>Description</th>
    <th>Image</th>
    <th>Prix</th>
    <th>Archivé</th>
    <th>Nouveauté</th>
    <th>Best seller</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($produits as $produit) : ?>
<tr>
    <td><?php echo $this->escapeHtml($produit->nom);?></td>
    <td><?php echo $this->escapeHtml($produit->reference);?></td>
    <td><?php echo $this->escapeHtml($produit->description);?></td>
    <td><?php echo $this->escapeHtml($produit->url_img);?></td>
    <td><?php echo $this->escapeHtml($produit->prix);?></td>
    <td><?php echo $this->escapeHtml($produit->bl_archive);?></td>
    <td><?php echo $this->escapeHtml($produit->bl_nouv);?></td>
    <td><?php echo $this->escapeHtml($produit->bl_best);?></td>
    <td>
        <a href="<?php echo $this->url('produit', array('action'=>'edit', 'id' => $produit->id_prod));?>">Edit</a>
        <a href="<?php echo $this->url('produit', array('action'=>'delete', 'id' => $produit->id_prod));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
