<div class="panel panel-default">
  <div class="panel-body">
		<form class="form-horizontal">
		  <fieldset>
		    <legend>Inscription</legend>
		    <div class="form-group">
		      <label class="col-lg-2 control-label">Civilité</label>
		      <div class="col-lg-10">
		        <div class="radio">
		          <label>
		            <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
		            Mr
		          </label>
		        </div>
		        <div class="radio">
		          <label>
		            <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
		            Mme
		          </label>
		        </div>
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="inputPrenom" class="col-lg-2 control-label">Prénom</label>
		      <div class="col-lg-10">
		        <input type="text" class="form-control" id="inputPrenom" placeholder="Prenom">
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="inputNom" class="col-lg-2 control-label">Nom</label>
		      <div class="col-lg-10">
		        <input type="text" class="form-control" id="inputNom" placeholder="Nom">
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
		      <div class="col-lg-10">
		        <input type="text" class="form-control" id="inputEmail" placeholder="Email">
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="inputPassword" class="col-lg-2 control-label">Mot de passe</label>
		      <div class="col-lg-10">
		        <input type="password" class="form-control" id="inputPassword" placeholder="Mot de passe">
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="inputPassword" class="col-lg-2 control-label">Confirmation</label>
		      <div class="col-lg-10">
		        <input type="password" class="form-control" id="inputConfirmPassword" placeholder="Mot de passe">
		      </div>
		    </div>
		    <div class="form-group">
		      <div class="col-lg-10 col-lg-offset-2">
		        <button type="reset" class="btn btn-default">Annuler</button>
		        <button type="submit" class="btn btn-primary">Inscription</button>
		      </div>
		    </div>
		  </fieldset>
		</form>
	</div>
</div>
 
</div>
