

<div class="row">
  <h1><?php echo $produit[0]->nom; ?></h1>

  <div class="row">
	  <div class="col-md-6">
  			<p><img src="<?php echo $produit[0]->url_img; ?>" alt="<?php echo $produit[0]->nom; ?>" width="150" height="auto"></p><br>
	  </div>
	  <div class="col-md-6">
	  		<p>REF: <?php echo $produit[0]->reference; ?></p>
	  		<h3>Prix: <?php echo $produit[0]->prix; ?> €</h3><br>
	  		<p><a class="btn btn-primary btn-lg" href="<?php echo $this->url('liste', array('action' => 'nouvelleliste')); ?>">Ajouter a ma liste d'envies</a></p>
	  </div>
	</div>

  

    <div class="panel panel-default">
		<div class="panel-heading"><h4>Description</h4></div>
		<div class="panel-body">
			<p><?php echo $produit[0]->description; ?></p>
		</div>
	</div>
</div>





<!--?php

var_dump($produit);-->
