

<div class="row">
  <h1><?php echo $produit[0]->nom; ?></h1>
  <p><?php echo $produit[0]->reference; ?></p>

  	<img src="<?php echo $produit[0]->url_img; ?>" alt="<?php echo $produit[0]->nom; ?>" width="150" height="auto"><br>

    <div class="panel panel-default">
		<div class="panel-heading"><h4>Description</h4></div>
		<div class="panel-body">
			<p><?php echo $produit[0]->description; ?></p>
		</div>
	</div>

	<p><a class="btn btn-primary btn-lg" href="">Ajouter a ma liste d'envies</a></p>
</div>





<?php

var_dump($produit);
