<div class="row">
    <?php foreach ($produits as $produit) { ?>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail thumbnail-list">
      <img src="<?php echo $produit[0]->url_img; ?>" alt="<?php echo $produit[0]->nom; ?>" width="150" height="auto">
      <div class="caption">
        <h3><?php echo $produit[0]->nom; ?></h3>
        <p><?php echo substr($produit[0]->description, 0, 100) ?></p><br>
        <p><a href="<?php echo $this->url('produit', array('action' => 'fiche', 'id' => $produit[0]->id_prod)); ?>" class="btn btn-primary" role="button">En savoir plus</a></p>
        <?php if(!$user = $this->identity()){ ?>
        <p><a href="<?php echo $this->url('liste', array('action' => 'ajoutliste', 'id' => $produit[0]->id_prod)); ?>" class="btn btn-default" role="button">Ajouter à ma lise d'envies</a></p>
        <?php } ?>
      </div>
    </div>
  </div>
    <?php } ?>
</div>

<nav>
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>