<?php
$title = 'Modifier un utilisateur';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', 
    $this->url('utilisateur', array('action' => 'edit', 'id_util'=>$this->id_util)));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id_util')) . PHP_EOL;
echo $this->formRow($form->get('nom')) . PHP_EOL;
echo $this->formRow($form->get('prenom')) . PHP_EOL;
echo $this->formRow($form->get('email')) . PHP_EOL;
echo $this->formRow($form->get('bl_acti')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

