<?php 
$title = 'Utilisateurs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('utilisateur', array( 
        'action'=>'add'));?>">Ajouter un utilisateur</a></p>

<table class="table">
<tr>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Email</th>
    <th>Actif·ve</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($utilisateurs as $utilisateur) : ?>
<tr>
    <td><?php echo $this->escapeHtml($utilisateur->nom);?></td>
    <td><?php echo $this->escapeHtml($utilisateur->prenom);?></td>
    <td><?php echo $this->escapeHtml($utilisateur->email);?></td>
    <td><?php echo $this->escapeHtml($utilisateur->bl_acti);?></td>
    <td>
        <a href="<?php echo $this->url('utilisateur',
            array('action'=>'edit', 'id' => $utilisateur->id_util));?>">Edit</a>
        <a href="<?php echo $this->url('utilisateur',
            array('action'=>'delete', 'id' => $utilisateur->id_util));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
