<div class="panel panel-default">
  <div class="panel-body">
		<form class="form-horizontal"  action="<?php echo $this->url('compte', array('action' => 'connexion')); ?>" method="post">
		  <fieldset>
		    <legend>Connexion</legend>
		    <div class="form-group">
		      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
		      <div class="col-lg-10">
		        <?php echo $this->formRow($form->get('email')) . PHP_EOL; ?>
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="inputPassword" class="col-lg-2 control-label">Mot de passe</label>
		      <div class="col-lg-10">
		        <?php echo $this->formRow($form->get('password')) . PHP_EOL; ?>
		      </div>
		    </div>
		    <div class="form-group">
		      <div class="col-lg-10 col-lg-offset-2">
		        <?php echo $this->formInput($form->get('submit')) . PHP_EOL; ?>
		      </div>
		    </div>
		  </fieldset>
		</form>
	</div>
</div>

</div>
