<div class="panel panel-default">
  <div class="panel-body">
		<form class="form-horizontal">
		  <fieldset>
		    <legend>Connexion</legend>
		    <div class="form-group">
		      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
		      <div class="col-lg-10">
		        <input type="text" class="form-control" id="inputEmail" placeholder="Email">
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="inputPassword" class="col-lg-2 control-label">Mot de passe</label>
		      <div class="col-lg-10">
		        <input type="password" class="form-control" id="inputPassword" placeholder="Mot de passe">
		      </div>
		    </div>
		    <div class="form-group">
		      <div class="col-lg-10 col-lg-offset-2">
		        <button type="reset" class="btn btn-default">Annuler</button>
		        <button type="submit" class="btn btn-primary">Connexion</button>
		      </div>
		    </div>
		  </fieldset>
		</form>
	</div>
</div>

</div>
