<?php
$form = $this->form;
$form->setAttribute('action', $this->url('compte', array('action' => 'inscription')));
$form->prepare();
?>

<div class="panel panel-default">
  <div class="panel-body">
		<form class="form-horizontal" action="/compte/inscription" method="post">
		  <fieldset>
		    <legend>Inscription</legend>
		    <div class="form-group">
		      <label for="inputPrenom" class="col-lg-2 control-label">Prénom</label>
		      <div class="col-lg-10">
		        <?php echo $this->formRow($form->get('prenom')) . PHP_EOL; ?>
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="inputNom" class="col-lg-2 control-label">Nom</label>
		      <div class="col-lg-10">
		        <?php echo $this->formRow($form->get('nom')) . PHP_EOL; ?>
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
		      <div class="col-lg-10">
		        <?php echo $this->formRow($form->get('email')) . PHP_EOL; ?>
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="inputPassword" class="col-lg-2 control-label">Mot de passe</label>
		      <div class="col-lg-10">
		        <?php echo $this->formRow($form->get('motdepasse')) . PHP_EOL; ?>
		      </div>
		    </div>
		    <div class="form-group">
		      <label for="inputPassword" class="col-lg-2 control-label">Confirmation</label>
		      <div class="col-lg-10">
		        <?php echo $this->formRow($form->get('confmotdepasse')) . PHP_EOL; ?>
		      </div>
		    </div>
		    <div class="form-group">
		      <div class="col-lg-10 col-lg-offset-2">
                          <?php echo $this->formInput($form->get('submit')) . PHP_EOL; ?>
		      </div>
		    </div>
		  </fieldset>
		</form>
	</div>
</div>
 
</div>
