<div class="row">
    <?php foreach ($produits as $produit) { ?>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail thumbnail-list">
      <img src="<?php echo $produit[0]->url_img; ?>" alt="<?php echo $produit[0]->nom; ?>" width="150" height="auto">
      <div class="caption">
        <h3><?php echo $produit[0]->nom; ?></h3>
        <p><?php echo substr($produit[0]->description, 0, 200) ?></p><br>
        <p><a href="<?php echo $this->url('produit', array('action' => 'fiche', 'id' => $produit[0]->id_prod)); ?>" class="btn btn-primary" role="button">En savoir plus</a></p>
        <p><a href="#" class="btn btn-default" role="button">Ajouter à ma lise d'envies</a></p>
      </div>
    </div>
  </div>
    <?php } ?>
</div>