<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Super site vitrine '. $this->translate('| Bienvenue'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                    ->appendStylesheet($this->basePath() . '/css/style.css')
                    ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->appendFile($this->basePath() . '/js/jquery-1.7.2.min.js')
                                  ->appendFile($this->basePath() . '/js/main.js') ?>

  </head>

  <body>

    <nav class="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <ul class="nav navbar-nav">
            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Accueil') ?></a></li>
            <li><a href="<?php echo $this->url('categorie',array('action' => 'liste')); ?>"><?php echo $this->translate('Tous nos livres') ?></a></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Catégories<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <?php if($this->layout()->categories != null){
                    foreach ($this->layout()->categories as $categ){ ?>
                    <li><a href="<?php echo $this->url('categorie',array('action' => 'liste', 'id' => $categ->nom)); ?>"><?php echo $categ->nom; ?></a></li>
                    <?php  } 
                    }?>
              </ul>
            </li>

            <li><a href="<?php echo $this->url('front',array('action' => 'contact')); ?>">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?php echo $this->url('compte',array('action' => 'connexion')); ?>">Connexion</a></li>
            <li><a href="<?php echo $this->url('compte',array('action' => 'inscription')); ?>">Inscription</a></li>
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <div class="panel-footer">Copyright Site vitrine - 2016 tous droits réservés</div>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
