<div class="row">
    <div class=".col-lg-12">
        <div class="jumbotron">
          <h1>Bienvenue sur notre nouvau site internet</h1>
          <p>Pour fêter la sortie de notre tout nouveau site internet, bénficiez de -50% sur les romans</p>
          <p><a class="btn btn-primary btn-lg" href="<?php echo $this->url('categorie',array('action' => 'liste')); ?>">En savoir plus</a></p>
        </div>
    </div>

    <div class="panel panel-default">
	  <div class="panel-heading"><h4>Nouveautés</h4></div>
	  <div class="panel-body">
	  	<div class="row">
		  <div class="col-sm-6 col-md-4">
		    <div class="thumbnail">
		      <img src="..." alt="...">
		      <div class="caption">
		        <h5>Thumbnail label</h5>
		        <p><a href="#" class="btn btn-primary" role="button">Button</a></p>
		      </div>
		    </div>
		  </div>

		  <div class="col-sm-6 col-md-4">
		    <div class="thumbnail">
		      <img src="..." alt="...">
		      <div class="caption">
		        <h5>Thumbnail label</h5>
		        <p><a href="#" class="btn btn-primary" role="button">Button</a></p>
		      </div>
		    </div>
		  </div>

		  <div class="col-sm-6 col-md-4">
		    <div class="thumbnail">
		      <img src="..." alt="...">
		      <div class="caption">
		        <h5>Thumbnail label</h5>
		        <p><a href="#" class="btn btn-primary" role="button">Button</a></p>
		      </div>
		    </div>
		  </div>
		</div>
	  </div>
	</div>

	<div class="panel panel-default">
	  <div class="panel-heading"><h4>Best sellers</h4></div>
	  <div class="panel-body">
	    <div class="row">
		  <div class="col-sm-6 col-md-4">
		    <div class="thumbnail">
		      <img src="..." alt="...">
		      <div class="caption">
		        <h5>Thumbnail label</h5>
		        <p><a href="#" class="btn btn-primary" role="button">En savoir plus</a></p>
		      </div>
		    </div>
		  </div>

		  <!--<div class="col-sm-6 col-md-4">
		    <div class="thumbnail">
		      <img src="<?php echo $produit[0]->url_img; ?>" alt="<?php echo $produit[0]->nom; ?>" width="150" height="auto">
		      <div class="caption">
		        <h5>Kafka sur le rivage</h5>
		        <p><a href="<?php echo $this->url('produit', array('action' => 'fiche', 'id' => $produit[0]->id_prod)); ?>" class="btn btn-primary" role="button">En savoir plus</a></p>
		      </div>
		    </div>
		  </div>-->

		  <div class="col-sm-6 col-md-4">
		    <div class="thumbnail">
		      <img src="..." alt="...">
		      <div class="caption">
		        <h5>Thumbnail label</h5>
		        <p><a href="#" class="btn btn-primary" role="button">En savoir plus</a></p>
		      </div>
		    </div>
		  </div>
		</div>
	  </div>
	</div>
	  </div>
	</div>

</div>
