<?php
$title = 'Ajouter une categorie';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('categorie', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id_categ')) . PHP_EOL;
echo $this->formRow($form->get('nom')) . PHP_EOL;
echo $this->formRow($form->get('url_img')) . PHP_EOL;
echo $this->formRow($form->get('description')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

