<?php
$title = 'Archiver une categorie';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Êtes-vous sûr·e de vouloir archiver cette categorie : 
  '<?php echo $this->escapeHtml($categorie->nom); ?>' ?
</p>
<?php 
$url = $this->url('categorie', array('action' => 'delete', 'id_categ'=>$this->id_categ)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id_categ" value="<?php echo (int)$categorie->id_categ; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>
